Support Exp
Idein/nnoir pull request #121
Opened 2021-07-05 11:27 UTC by nomaddo

- Support Exp

2021-07-06 14:31 UTC, notogawa reviewed
plz. add `test_Exp` to [`nnoir/test/test_run.py`](https://github.com/Idein/nnoir/blob/append_exp/nnoir/test/test_run.py)

2021-07-07 00:23 UTC, nomaddo commented
> plz. add test_Exp to nnoir/test/test_run.py

Fixed in cb58ef2

2021-07-07 00:27 UTC, notogawa requested changes

2021-07-07 00:27 UTC, notogawa commented on nnoir/test/test_run.py
> +def test_Exp():
plz move `test_Exp` to between `test_ELU` and `test_Gemm` to keep lexicographic order.

2021-07-07 00:30 UTC, notogawa approved these changes
LGTM

2021-07-07 00:43 UTC, ishiy1993 approved these changes
LGTM

2021-07-07 00:43 UTC, nomaddo commented
🙏

2021-07-07 00:43 UTC, merged